# Generated by Django 5.0.2 on 2024-02-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambot',
            old_name='_name',
            new_name='_title',
        ),
        migrations.RenameField(
            model_name='telegrambot',
            old_name='name',
            new_name='title',
        ),
    ]
