# Generated by Django 5.0.2 on 2024-02-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_telegrambot_users_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='users_count',
        ),
    ]
