# Generated by Django 5.0.2 on 2024-03-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_telegrambot_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='_bot_token',
        ),
        migrations.RemoveField(
            model_name='telegrambot',
            name='_title',
        ),
    ]
