# Generated by Django 5.0.2 on 2024-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_remove_telegrambot__bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=15),
        ),
    ]
