# Generated by Django 5.0.2 on 2024-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_telegrambot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='status',
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
