# Generated by Django 5.0.2 on 2024-03-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_alter_telegrambot_bot_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambot',
            old_name='title',
            new_name='bot_name',
        ),
    ]
