# Generated by Django 5.0.2 on 2024-03-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_rename_title_telegrambot_bot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambot',
            old_name='is_activated',
            new_name='is_active',
        ),
    ]
